package domain.dao;

import domain.model.EqpmentLog;
import domain.model.EqpmentLogExample;

import java.sql.SQLException;
import java.util.List;

public interface EqpmentLogDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplistlog
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    void insert(EqpmentLog record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplistlog
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    int updateByPrimaryKey(EqpmentLog record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplistlog
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    int updateByPrimaryKeySelective(EqpmentLog record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplistlog
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    List selectByExample(EqpmentLogExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplistlog
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    EqpmentLog selectByPrimaryKey(Integer quipid) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplistlog
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    int deleteByExample(EqpmentLogExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplistlog
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    int deleteByPrimaryKey(Integer quipid) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplistlog
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    int countByExample(EqpmentLogExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplistlog
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    int updateByExampleSelective(EqpmentLog record, EqpmentLogExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplistlog
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    int updateByExample(EqpmentLog record, EqpmentLogExample example) throws SQLException;
}