package domain.dao;

import domain.model.Eqpment;
import domain.model.EqpmentExample;

import java.sql.SQLException;
import java.util.List;

public interface EqpmentDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplist
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    void insert(Eqpment record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplist
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    int updateByPrimaryKey(Eqpment record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplist
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    int updateByPrimaryKeySelective(Eqpment record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplist
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    List selectByExample(EqpmentExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplist
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    Eqpment selectByPrimaryKey(Integer eqplistlogid) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplist
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    int deleteByExample(EqpmentExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplist
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    int deleteByPrimaryKey(Integer eqplistlogid) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplist
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    int countByExample(EqpmentExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplist
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    int updateByExampleSelective(Eqpment record, EqpmentExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplist
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    int updateByExample(Eqpment record, EqpmentExample example) throws SQLException;
}