package domain.dao;

import domain.model.Eqpment;
import domain.model.EqpmentExample;

import java.sql.SQLException;
import java.util.List;
//import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EqpmentDAOImpl extends SqlMapClientDaoSupport implements EqpmentDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplist
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public EqpmentDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplist
     * @throws SQLException 
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public void insert(Eqpment record) throws SQLException  {
        getSqlMapClientTemplate().insert("eqplist.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplist
     * @throws SQLException 
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public int updateByPrimaryKey(Eqpment record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("eqplist.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplist
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public int updateByPrimaryKeySelective(Eqpment record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("eqplist.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplist
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public List selectByExample(EqpmentExample example) throws SQLException {
        List list = getSqlMapClientTemplate().queryForList("eqplist.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplist
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public Eqpment selectByPrimaryKey(Integer eqplistlogid) throws SQLException {
        Eqpment key = new Eqpment();
        key.setEqplistlogid(eqplistlogid);
        Eqpment record = (Eqpment) getSqlMapClientTemplate().queryForObject("eqplist.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplist
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public int deleteByExample(EqpmentExample example) throws SQLException {
        int rows = getSqlMapClientTemplate().delete("eqplist.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplist
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public int deleteByPrimaryKey(Integer eqplistlogid) throws SQLException {
        Eqpment key = new Eqpment();
        key.setEqplistlogid(eqplistlogid);
        int rows = getSqlMapClientTemplate().delete("eqplist.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplist
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public int countByExample(EqpmentExample example) throws SQLException {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("eqplist.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplist
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public int updateByExampleSelective(Eqpment record, EqpmentExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("eqplist.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplist
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public int updateByExample(Eqpment record, EqpmentExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("eqplist.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table eqplist
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    private static class UpdateByExampleParms extends EqpmentExample {
        private Object record;

        public UpdateByExampleParms(Object record, EqpmentExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}