package domain.dao;

import domain.model.EqpmentLog;
import domain.model.EqpmentLogExample;

import java.sql.SQLException;
import java.util.List;
//import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EqpmentLogDAOImpl extends SqlMapClientDaoSupport implements EqpmentLogDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplistlog
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public EqpmentLogDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplistlog
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public void insert(EqpmentLog record) throws SQLException {
        getSqlMapClientTemplate().insert("eqplistlog.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplistlog
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public int updateByPrimaryKey(EqpmentLog record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("eqplistlog.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplistlog
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public int updateByPrimaryKeySelective(EqpmentLog record) throws SQLException {
        int rows = getSqlMapClientTemplate().update("eqplistlog.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplistlog
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public List selectByExample(EqpmentLogExample example) throws SQLException {
        List list = getSqlMapClientTemplate().queryForList("eqplistlog.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplistlog
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public EqpmentLog selectByPrimaryKey(Integer quipid) throws SQLException {
        EqpmentLog key = new EqpmentLog();
        key.setQuipid(quipid);
        EqpmentLog record = (EqpmentLog) getSqlMapClientTemplate().queryForObject("eqplistlog.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplistlog
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public int deleteByExample(EqpmentLogExample example) throws SQLException {
        int rows = getSqlMapClientTemplate().delete("eqplistlog.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplistlog
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public int deleteByPrimaryKey(Integer quipid) throws SQLException {
        EqpmentLog key = new EqpmentLog();
        key.setQuipid(quipid);
        int rows = getSqlMapClientTemplate().delete("eqplistlog.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplistlog
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public int countByExample(EqpmentLogExample example) throws SQLException {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("eqplistlog.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplistlog
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public int updateByExampleSelective(EqpmentLog record, EqpmentLogExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("eqplistlog.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eqplistlog
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public int updateByExample(EqpmentLog record, EqpmentLogExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("eqplistlog.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table eqplistlog
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    private static class UpdateByExampleParms extends EqpmentLogExample {
        private Object record;

        public UpdateByExampleParms(Object record, EqpmentLogExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}