package domain.dao;

import domain.model.EventLog;
import domain.model.EventLogExample;

import java.sql.SQLException;
import java.util.List;
//import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EventLogDAOImpl extends SqlMapClientDaoSupport implements EventLogDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eventlistLog
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    public EventLogDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eventlistLog
     * @throws SQLException 
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    public void insert(EventLog record) throws SQLException {
        getSqlMapClientTemplate().insert("eventlistLog.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eventlistLog
     * @throws SQLException 
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    public List selectByExample(EventLogExample example) throws SQLException {
        List list = getSqlMapClientTemplate().queryForList("eventlistLog.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eventlistLog
     * @throws SQLException 
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    public int deleteByExample(EventLogExample example) throws SQLException {
        int rows = getSqlMapClientTemplate().delete("eventlistLog.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eventlistLog
     * @throws SQLException 
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    public int countByExample(EventLogExample example) throws SQLException {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("eventlistLog.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eventlistLog
     * @throws SQLException 
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    public int updateByExampleSelective(EventLog record, EventLogExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("eventlistLog.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eventlistLog
     * @throws SQLException 
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    public int updateByExample(EventLog record, EventLogExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("eventlistLog.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table eventlistLog
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    private static class UpdateByExampleParms extends EventLogExample {
        private Object record;

        public UpdateByExampleParms(Object record, EventLogExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}