package domain.dao;

import domain.model.Event;
import domain.model.EventExample;

import java.sql.SQLException;
import java.util.List;

public interface EventDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eventlist
     * @throws SQLException 
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    void insert(Event record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eventlist
     * @throws SQLException 
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    int updateByPrimaryKey(Event record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eventlist
     * @throws SQLException 
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    int updateByPrimaryKeySelective(Event record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eventlist
     * @throws SQLException 
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    List selectByExample(EventExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eventlist
     * @throws SQLException 
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    Event selectByPrimaryKey(Integer eventid) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eventlist
     * @throws SQLException 
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    int deleteByExample(EventExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eventlist
     * @throws SQLException 
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    int deleteByPrimaryKey(Integer eventid) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eventlist
     * @throws SQLException 
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    int countByExample(EventExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eventlist
     * @throws SQLException 
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    int updateByExampleSelective(Event record, EventExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eventlist
     * @throws SQLException 
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    int updateByExample(Event record, EventExample example) throws SQLException;
}