package domain.dao;

import domain.model.EventLog;
import domain.model.EventLogExample;

import java.sql.SQLException;
import java.util.List;

public interface EventLogDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eventlistLog
     * @throws SQLException 
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    void insert(EventLog record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eventlistLog
     * @throws SQLException 
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    List selectByExample(EventLogExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eventlistLog
     * @throws SQLException 
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    int deleteByExample(EventLogExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eventlistLog
     * @throws SQLException 
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    int countByExample(EventLogExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eventlistLog
     * @throws SQLException 
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    int updateByExampleSelective(EventLog record, EventLogExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table eventlistLog
     * @throws SQLException 
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    int updateByExample(EventLog record, EventLogExample example) throws SQLException;
}