package domain.dao;

import domain.model.Sac_deepsky;
import domain.model.Sac_deepskyExample;

import java.sql.SQLException;
import java.util.List;
//import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class Sac_deepskyDAOImpl extends SqlMapClientDaoSupport implements Sac_deepskyDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sac_deepsky
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public Sac_deepskyDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sac_deepsky
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public void insert(Sac_deepsky record) throws SQLException {
        getSqlMapClientTemplate().insert("sac_deepsky.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sac_deepsky
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public List selectByExample(Sac_deepskyExample example) throws SQLException {
        List list = getSqlMapClientTemplate().queryForList("sac_deepsky.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sac_deepsky
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public int deleteByExample(Sac_deepskyExample example) throws SQLException {
        int rows = getSqlMapClientTemplate().delete("sac_deepsky.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sac_deepsky
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public int countByExample(Sac_deepskyExample example) throws SQLException {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("sac_deepsky.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sac_deepsky
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public int updateByExampleSelective(Sac_deepsky record, Sac_deepskyExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("sac_deepsky.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sac_deepsky
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public int updateByExample(Sac_deepsky record, Sac_deepskyExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("sac_deepsky.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table sac_deepsky
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    private static class UpdateByExampleParms extends Sac_deepskyExample {
        private Object record;

        public UpdateByExampleParms(Object record, Sac_deepskyExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}