package domain.dao;

import domain.model.Sac_deepsky;
import domain.model.Sac_deepskyExample;

import java.sql.SQLException;
import java.util.List;

public interface Sac_deepskyDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sac_deepsky
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    void insert(Sac_deepsky record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sac_deepsky
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    List selectByExample(Sac_deepskyExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sac_deepsky
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    int deleteByExample(Sac_deepskyExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sac_deepsky
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    int countByExample(Sac_deepskyExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sac_deepsky
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    int updateByExampleSelective(Sac_deepsky record, Sac_deepskyExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sac_deepsky
     * @throws SQLException 
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    int updateByExample(Sac_deepsky record, Sac_deepskyExample example) throws SQLException;
}