package domain.model;

public class Eqpment {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column eqplist.eqplistlogid
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    private Integer eqplistlogid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column eqplist.quipname
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    private String quipname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column eqplist.quipid
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    private Integer quipid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column eqplist.quipstats
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    private String quipstats;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column eqplist.sitelocation
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    private Integer sitelocation;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column eqplist.sitename
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    private Integer sitename;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column eqplist.eqplistlogid
     *
     * @return the value of eqplist.eqplistlogid
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public Integer getEqplistlogid() {
        return eqplistlogid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column eqplist.eqplistlogid
     *
     * @param eqplistlogid the value for eqplist.eqplistlogid
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public void setEqplistlogid(Integer eqplistlogid) {
        this.eqplistlogid = eqplistlogid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column eqplist.quipname
     *
     * @return the value of eqplist.quipname
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public String getQuipname() {
        return quipname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column eqplist.quipname
     *
     * @param quipname the value for eqplist.quipname
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public void setQuipname(String quipname) {
        this.quipname = quipname == null ? null : quipname.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column eqplist.quipid
     *
     * @return the value of eqplist.quipid
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public Integer getQuipid() {
        return quipid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column eqplist.quipid
     *
     * @param quipid the value for eqplist.quipid
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public void setQuipid(Integer quipid) {
        this.quipid = quipid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column eqplist.quipstats
     *
     * @return the value of eqplist.quipstats
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public String getQuipstats() {
        return quipstats;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column eqplist.quipstats
     *
     * @param quipstats the value for eqplist.quipstats
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public void setQuipstats(String quipstats) {
        this.quipstats = quipstats == null ? null : quipstats.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column eqplist.sitelocation
     *
     * @return the value of eqplist.sitelocation
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public Integer getSitelocation() {
        return sitelocation;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column eqplist.sitelocation
     *
     * @param sitelocation the value for eqplist.sitelocation
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public void setSitelocation(Integer sitelocation) {
        this.sitelocation = sitelocation;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column eqplist.sitename
     *
     * @return the value of eqplist.sitename
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public Integer getSitename() {
        return sitename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column eqplist.sitename
     *
     * @param sitename the value for eqplist.sitename
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public void setSitename(Integer sitename) {
        this.sitename = sitename;
    }
}