package domain.model;

public class EqpmentLog {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column eqplistlog.quipid
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    private Integer quipid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column eqplistlog.quipname
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    private String quipname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column eqplistlog.quipstats
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    private String quipstats;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column eqplistlog.sitelocation
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    private Integer sitelocation;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column eqplistlog.sitename
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    private Integer sitename;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column eqplistlog.optiontime
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    private String optiontime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column eqplistlog.optiontype
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    private String optiontype;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column eqplistlog.quipid
     *
     * @return the value of eqplistlog.quipid
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public Integer getQuipid() {
        return quipid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column eqplistlog.quipid
     *
     * @param quipid the value for eqplistlog.quipid
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public void setQuipid(Integer quipid) {
        this.quipid = quipid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column eqplistlog.quipname
     *
     * @return the value of eqplistlog.quipname
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public String getQuipname() {
        return quipname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column eqplistlog.quipname
     *
     * @param quipname the value for eqplistlog.quipname
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public void setQuipname(String quipname) {
        this.quipname = quipname == null ? null : quipname.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column eqplistlog.quipstats
     *
     * @return the value of eqplistlog.quipstats
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public String getQuipstats() {
        return quipstats;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column eqplistlog.quipstats
     *
     * @param quipstats the value for eqplistlog.quipstats
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public void setQuipstats(String quipstats) {
        this.quipstats = quipstats == null ? null : quipstats.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column eqplistlog.sitelocation
     *
     * @return the value of eqplistlog.sitelocation
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public Integer getSitelocation() {
        return sitelocation;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column eqplistlog.sitelocation
     *
     * @param sitelocation the value for eqplistlog.sitelocation
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public void setSitelocation(Integer sitelocation) {
        this.sitelocation = sitelocation;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column eqplistlog.sitename
     *
     * @return the value of eqplistlog.sitename
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public Integer getSitename() {
        return sitename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column eqplistlog.sitename
     *
     * @param sitename the value for eqplistlog.sitename
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public void setSitename(Integer sitename) {
        this.sitename = sitename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column eqplistlog.optiontime
     *
     * @return the value of eqplistlog.optiontime
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public String getOptiontime() {
        return optiontime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column eqplistlog.optiontime
     *
     * @param optiontime the value for eqplistlog.optiontime
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public void setOptiontime(String optiontime) {
        this.optiontime = optiontime == null ? null : optiontime.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column eqplistlog.optiontype
     *
     * @return the value of eqplistlog.optiontype
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public String getOptiontype() {
        return optiontype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column eqplistlog.optiontype
     *
     * @param optiontype the value for eqplistlog.optiontype
     *
     * @abatorgenerated Wed Mar 15 19:59:10 CST 2017
     */
    public void setOptiontype(String optiontype) {
        this.optiontype = optiontype == null ? null : optiontype.trim();
    }
}