package domain.model;

public class Event {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column eventlist.eventid
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    private Integer eventid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column eventlist.eqpid
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    private Integer eqpid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column eventlist.title
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    private String title;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column eventlist.starttime
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    private String starttime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column eventlist.endtime
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    private String endtime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column eventlist.userid
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    private Integer userid;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column eventlist.eventid
     *
     * @return the value of eventlist.eventid
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    public Integer getEventid() {
        return eventid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column eventlist.eventid
     *
     * @param eventid the value for eventlist.eventid
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    public void setEventid(Integer eventid) {
        this.eventid = eventid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column eventlist.eqpid
     *
     * @return the value of eventlist.eqpid
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    public Integer getEqpid() {
        return eqpid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column eventlist.eqpid
     *
     * @param eqpid the value for eventlist.eqpid
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    public void setEqpid(Integer eqpid) {
        this.eqpid = eqpid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column eventlist.title
     *
     * @return the value of eventlist.title
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column eventlist.title
     *
     * @param title the value for eventlist.title
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column eventlist.starttime
     *
     * @return the value of eventlist.starttime
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    public String getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column eventlist.starttime
     *
     * @param starttime the value for eventlist.starttime
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    public void setStarttime(String starttime) {
        this.starttime = starttime == null ? null : starttime.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column eventlist.endtime
     *
     * @return the value of eventlist.endtime
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    public String getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column eventlist.endtime
     *
     * @param endtime the value for eventlist.endtime
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    public void setEndtime(String endtime) {
        this.endtime = endtime == null ? null : endtime.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column eventlist.userid
     *
     * @return the value of eventlist.userid
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column eventlist.userid
     *
     * @param userid the value for eventlist.userid
     *
     * @abatorgenerated Fri Mar 17 21:28:15 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}