package domain.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class Sac_deepskyExample {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sac_deepsky
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sac_deepsky
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    protected List oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sac_deepsky
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public Sac_deepskyExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sac_deepsky
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    protected Sac_deepskyExample(Sac_deepskyExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sac_deepsky
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sac_deepsky
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sac_deepsky
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sac_deepsky
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sac_deepsky
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sac_deepsky
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sac_deepsky
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table sac_deepsky
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andObjectIsNull() {
            addCriterion("object is null");
            return this;
        }

        public Criteria andObjectIsNotNull() {
            addCriterion("object is not null");
            return this;
        }

        public Criteria andObjectEqualTo(String value) {
            addCriterion("object =", value, "object");
            return this;
        }

        public Criteria andObjectNotEqualTo(String value) {
            addCriterion("object <>", value, "object");
            return this;
        }

        public Criteria andObjectGreaterThan(String value) {
            addCriterion("object >", value, "object");
            return this;
        }

        public Criteria andObjectGreaterThanOrEqualTo(String value) {
            addCriterion("object >=", value, "object");
            return this;
        }

        public Criteria andObjectLessThan(String value) {
            addCriterion("object <", value, "object");
            return this;
        }

        public Criteria andObjectLessThanOrEqualTo(String value) {
            addCriterion("object <=", value, "object");
            return this;
        }

        public Criteria andObjectLike(String value) {
            addCriterion("object like", value, "object");
            return this;
        }

        public Criteria andObjectNotLike(String value) {
            addCriterion("object not like", value, "object");
            return this;
        }

        public Criteria andObjectIn(List values) {
            addCriterion("object in", values, "object");
            return this;
        }

        public Criteria andObjectNotIn(List values) {
            addCriterion("object not in", values, "object");
            return this;
        }

        public Criteria andObjectBetween(String value1, String value2) {
            addCriterion("object between", value1, value2, "object");
            return this;
        }

        public Criteria andObjectNotBetween(String value1, String value2) {
            addCriterion("object not between", value1, value2, "object");
            return this;
        }

        public Criteria andOtherIsNull() {
            addCriterion("other is null");
            return this;
        }

        public Criteria andOtherIsNotNull() {
            addCriterion("other is not null");
            return this;
        }

        public Criteria andOtherEqualTo(String value) {
            addCriterion("other =", value, "other");
            return this;
        }

        public Criteria andOtherNotEqualTo(String value) {
            addCriterion("other <>", value, "other");
            return this;
        }

        public Criteria andOtherGreaterThan(String value) {
            addCriterion("other >", value, "other");
            return this;
        }

        public Criteria andOtherGreaterThanOrEqualTo(String value) {
            addCriterion("other >=", value, "other");
            return this;
        }

        public Criteria andOtherLessThan(String value) {
            addCriterion("other <", value, "other");
            return this;
        }

        public Criteria andOtherLessThanOrEqualTo(String value) {
            addCriterion("other <=", value, "other");
            return this;
        }

        public Criteria andOtherLike(String value) {
            addCriterion("other like", value, "other");
            return this;
        }

        public Criteria andOtherNotLike(String value) {
            addCriterion("other not like", value, "other");
            return this;
        }

        public Criteria andOtherIn(List values) {
            addCriterion("other in", values, "other");
            return this;
        }

        public Criteria andOtherNotIn(List values) {
            addCriterion("other not in", values, "other");
            return this;
        }

        public Criteria andOtherBetween(String value1, String value2) {
            addCriterion("other between", value1, value2, "other");
            return this;
        }

        public Criteria andOtherNotBetween(String value1, String value2) {
            addCriterion("other not between", value1, value2, "other");
            return this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return this;
        }

        public Criteria andTypeIn(List values) {
            addCriterion("type in", values, "type");
            return this;
        }

        public Criteria andTypeNotIn(List values) {
            addCriterion("type not in", values, "type");
            return this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return this;
        }

        public Criteria andConIsNull() {
            addCriterion("con is null");
            return this;
        }

        public Criteria andConIsNotNull() {
            addCriterion("con is not null");
            return this;
        }

        public Criteria andConEqualTo(String value) {
            addCriterion("con =", value, "con");
            return this;
        }

        public Criteria andConNotEqualTo(String value) {
            addCriterion("con <>", value, "con");
            return this;
        }

        public Criteria andConGreaterThan(String value) {
            addCriterion("con >", value, "con");
            return this;
        }

        public Criteria andConGreaterThanOrEqualTo(String value) {
            addCriterion("con >=", value, "con");
            return this;
        }

        public Criteria andConLessThan(String value) {
            addCriterion("con <", value, "con");
            return this;
        }

        public Criteria andConLessThanOrEqualTo(String value) {
            addCriterion("con <=", value, "con");
            return this;
        }

        public Criteria andConLike(String value) {
            addCriterion("con like", value, "con");
            return this;
        }

        public Criteria andConNotLike(String value) {
            addCriterion("con not like", value, "con");
            return this;
        }

        public Criteria andConIn(List values) {
            addCriterion("con in", values, "con");
            return this;
        }

        public Criteria andConNotIn(List values) {
            addCriterion("con not in", values, "con");
            return this;
        }

        public Criteria andConBetween(String value1, String value2) {
            addCriterion("con between", value1, value2, "con");
            return this;
        }

        public Criteria andConNotBetween(String value1, String value2) {
            addCriterion("con not between", value1, value2, "con");
            return this;
        }

        public Criteria andRa_hrIsNull() {
            addCriterion("ra_hr is null");
            return this;
        }

        public Criteria andRa_hrIsNotNull() {
            addCriterion("ra_hr is not null");
            return this;
        }

        public Criteria andRa_hrEqualTo(String value) {
            addCriterion("ra_hr =", value, "ra_hr");
            return this;
        }

        public Criteria andRa_hrNotEqualTo(String value) {
            addCriterion("ra_hr <>", value, "ra_hr");
            return this;
        }

        public Criteria andRa_hrGreaterThan(String value) {
            addCriterion("ra_hr >", value, "ra_hr");
            return this;
        }

        public Criteria andRa_hrGreaterThanOrEqualTo(String value) {
            addCriterion("ra_hr >=", value, "ra_hr");
            return this;
        }

        public Criteria andRa_hrLessThan(String value) {
            addCriterion("ra_hr <", value, "ra_hr");
            return this;
        }

        public Criteria andRa_hrLessThanOrEqualTo(String value) {
            addCriterion("ra_hr <=", value, "ra_hr");
            return this;
        }

        public Criteria andRa_hrLike(String value) {
            addCriterion("ra_hr like", value, "ra_hr");
            return this;
        }

        public Criteria andRa_hrNotLike(String value) {
            addCriterion("ra_hr not like", value, "ra_hr");
            return this;
        }

        public Criteria andRa_hrIn(List values) {
            addCriterion("ra_hr in", values, "ra_hr");
            return this;
        }

        public Criteria andRa_hrNotIn(List values) {
            addCriterion("ra_hr not in", values, "ra_hr");
            return this;
        }

        public Criteria andRa_hrBetween(String value1, String value2) {
            addCriterion("ra_hr between", value1, value2, "ra_hr");
            return this;
        }

        public Criteria andRa_hrNotBetween(String value1, String value2) {
            addCriterion("ra_hr not between", value1, value2, "ra_hr");
            return this;
        }

        public Criteria andRa_minIsNull() {
            addCriterion("ra_min is null");
            return this;
        }

        public Criteria andRa_minIsNotNull() {
            addCriterion("ra_min is not null");
            return this;
        }

        public Criteria andRa_minEqualTo(String value) {
            addCriterion("ra_min =", value, "ra_min");
            return this;
        }

        public Criteria andRa_minNotEqualTo(String value) {
            addCriterion("ra_min <>", value, "ra_min");
            return this;
        }

        public Criteria andRa_minGreaterThan(String value) {
            addCriterion("ra_min >", value, "ra_min");
            return this;
        }

        public Criteria andRa_minGreaterThanOrEqualTo(String value) {
            addCriterion("ra_min >=", value, "ra_min");
            return this;
        }

        public Criteria andRa_minLessThan(String value) {
            addCriterion("ra_min <", value, "ra_min");
            return this;
        }

        public Criteria andRa_minLessThanOrEqualTo(String value) {
            addCriterion("ra_min <=", value, "ra_min");
            return this;
        }

        public Criteria andRa_minLike(String value) {
            addCriterion("ra_min like", value, "ra_min");
            return this;
        }

        public Criteria andRa_minNotLike(String value) {
            addCriterion("ra_min not like", value, "ra_min");
            return this;
        }

        public Criteria andRa_minIn(List values) {
            addCriterion("ra_min in", values, "ra_min");
            return this;
        }

        public Criteria andRa_minNotIn(List values) {
            addCriterion("ra_min not in", values, "ra_min");
            return this;
        }

        public Criteria andRa_minBetween(String value1, String value2) {
            addCriterion("ra_min between", value1, value2, "ra_min");
            return this;
        }

        public Criteria andRa_minNotBetween(String value1, String value2) {
            addCriterion("ra_min not between", value1, value2, "ra_min");
            return this;
        }

        public Criteria andDec_degIsNull() {
            addCriterion("dec_deg is null");
            return this;
        }

        public Criteria andDec_degIsNotNull() {
            addCriterion("dec_deg is not null");
            return this;
        }

        public Criteria andDec_degEqualTo(String value) {
            addCriterion("dec_deg =", value, "dec_deg");
            return this;
        }

        public Criteria andDec_degNotEqualTo(String value) {
            addCriterion("dec_deg <>", value, "dec_deg");
            return this;
        }

        public Criteria andDec_degGreaterThan(String value) {
            addCriterion("dec_deg >", value, "dec_deg");
            return this;
        }

        public Criteria andDec_degGreaterThanOrEqualTo(String value) {
            addCriterion("dec_deg >=", value, "dec_deg");
            return this;
        }

        public Criteria andDec_degLessThan(String value) {
            addCriterion("dec_deg <", value, "dec_deg");
            return this;
        }

        public Criteria andDec_degLessThanOrEqualTo(String value) {
            addCriterion("dec_deg <=", value, "dec_deg");
            return this;
        }

        public Criteria andDec_degLike(String value) {
            addCriterion("dec_deg like", value, "dec_deg");
            return this;
        }

        public Criteria andDec_degNotLike(String value) {
            addCriterion("dec_deg not like", value, "dec_deg");
            return this;
        }

        public Criteria andDec_degIn(List values) {
            addCriterion("dec_deg in", values, "dec_deg");
            return this;
        }

        public Criteria andDec_degNotIn(List values) {
            addCriterion("dec_deg not in", values, "dec_deg");
            return this;
        }

        public Criteria andDec_degBetween(String value1, String value2) {
            addCriterion("dec_deg between", value1, value2, "dec_deg");
            return this;
        }

        public Criteria andDec_degNotBetween(String value1, String value2) {
            addCriterion("dec_deg not between", value1, value2, "dec_deg");
            return this;
        }

        public Criteria andDec_minIsNull() {
            addCriterion("dec_min is null");
            return this;
        }

        public Criteria andDec_minIsNotNull() {
            addCriterion("dec_min is not null");
            return this;
        }

        public Criteria andDec_minEqualTo(String value) {
            addCriterion("dec_min =", value, "dec_min");
            return this;
        }

        public Criteria andDec_minNotEqualTo(String value) {
            addCriterion("dec_min <>", value, "dec_min");
            return this;
        }

        public Criteria andDec_minGreaterThan(String value) {
            addCriterion("dec_min >", value, "dec_min");
            return this;
        }

        public Criteria andDec_minGreaterThanOrEqualTo(String value) {
            addCriterion("dec_min >=", value, "dec_min");
            return this;
        }

        public Criteria andDec_minLessThan(String value) {
            addCriterion("dec_min <", value, "dec_min");
            return this;
        }

        public Criteria andDec_minLessThanOrEqualTo(String value) {
            addCriterion("dec_min <=", value, "dec_min");
            return this;
        }

        public Criteria andDec_minLike(String value) {
            addCriterion("dec_min like", value, "dec_min");
            return this;
        }

        public Criteria andDec_minNotLike(String value) {
            addCriterion("dec_min not like", value, "dec_min");
            return this;
        }

        public Criteria andDec_minIn(List values) {
            addCriterion("dec_min in", values, "dec_min");
            return this;
        }

        public Criteria andDec_minNotIn(List values) {
            addCriterion("dec_min not in", values, "dec_min");
            return this;
        }

        public Criteria andDec_minBetween(String value1, String value2) {
            addCriterion("dec_min between", value1, value2, "dec_min");
            return this;
        }

        public Criteria andDec_minNotBetween(String value1, String value2) {
            addCriterion("dec_min not between", value1, value2, "dec_min");
            return this;
        }

        public Criteria andMagIsNull() {
            addCriterion("mag is null");
            return this;
        }

        public Criteria andMagIsNotNull() {
            addCriterion("mag is not null");
            return this;
        }

        public Criteria andMagEqualTo(String value) {
            addCriterion("mag =", value, "mag");
            return this;
        }

        public Criteria andMagNotEqualTo(String value) {
            addCriterion("mag <>", value, "mag");
            return this;
        }

        public Criteria andMagGreaterThan(String value) {
            addCriterion("mag >", value, "mag");
            return this;
        }

        public Criteria andMagGreaterThanOrEqualTo(String value) {
            addCriterion("mag >=", value, "mag");
            return this;
        }

        public Criteria andMagLessThan(String value) {
            addCriterion("mag <", value, "mag");
            return this;
        }

        public Criteria andMagLessThanOrEqualTo(String value) {
            addCriterion("mag <=", value, "mag");
            return this;
        }

        public Criteria andMagLike(String value) {
            addCriterion("mag like", value, "mag");
            return this;
        }

        public Criteria andMagNotLike(String value) {
            addCriterion("mag not like", value, "mag");
            return this;
        }

        public Criteria andMagIn(List values) {
            addCriterion("mag in", values, "mag");
            return this;
        }

        public Criteria andMagNotIn(List values) {
            addCriterion("mag not in", values, "mag");
            return this;
        }

        public Criteria andMagBetween(String value1, String value2) {
            addCriterion("mag between", value1, value2, "mag");
            return this;
        }

        public Criteria andMagNotBetween(String value1, String value2) {
            addCriterion("mag not between", value1, value2, "mag");
            return this;
        }

        public Criteria andSubrIsNull() {
            addCriterion("subr is null");
            return this;
        }

        public Criteria andSubrIsNotNull() {
            addCriterion("subr is not null");
            return this;
        }

        public Criteria andSubrEqualTo(String value) {
            addCriterion("subr =", value, "subr");
            return this;
        }

        public Criteria andSubrNotEqualTo(String value) {
            addCriterion("subr <>", value, "subr");
            return this;
        }

        public Criteria andSubrGreaterThan(String value) {
            addCriterion("subr >", value, "subr");
            return this;
        }

        public Criteria andSubrGreaterThanOrEqualTo(String value) {
            addCriterion("subr >=", value, "subr");
            return this;
        }

        public Criteria andSubrLessThan(String value) {
            addCriterion("subr <", value, "subr");
            return this;
        }

        public Criteria andSubrLessThanOrEqualTo(String value) {
            addCriterion("subr <=", value, "subr");
            return this;
        }

        public Criteria andSubrLike(String value) {
            addCriterion("subr like", value, "subr");
            return this;
        }

        public Criteria andSubrNotLike(String value) {
            addCriterion("subr not like", value, "subr");
            return this;
        }

        public Criteria andSubrIn(List values) {
            addCriterion("subr in", values, "subr");
            return this;
        }

        public Criteria andSubrNotIn(List values) {
            addCriterion("subr not in", values, "subr");
            return this;
        }

        public Criteria andSubrBetween(String value1, String value2) {
            addCriterion("subr between", value1, value2, "subr");
            return this;
        }

        public Criteria andSubrNotBetween(String value1, String value2) {
            addCriterion("subr not between", value1, value2, "subr");
            return this;
        }

        public Criteria andUranoIsNull() {
            addCriterion("urano is null");
            return this;
        }

        public Criteria andUranoIsNotNull() {
            addCriterion("urano is not null");
            return this;
        }

        public Criteria andUranoEqualTo(String value) {
            addCriterion("urano =", value, "urano");
            return this;
        }

        public Criteria andUranoNotEqualTo(String value) {
            addCriterion("urano <>", value, "urano");
            return this;
        }

        public Criteria andUranoGreaterThan(String value) {
            addCriterion("urano >", value, "urano");
            return this;
        }

        public Criteria andUranoGreaterThanOrEqualTo(String value) {
            addCriterion("urano >=", value, "urano");
            return this;
        }

        public Criteria andUranoLessThan(String value) {
            addCriterion("urano <", value, "urano");
            return this;
        }

        public Criteria andUranoLessThanOrEqualTo(String value) {
            addCriterion("urano <=", value, "urano");
            return this;
        }

        public Criteria andUranoLike(String value) {
            addCriterion("urano like", value, "urano");
            return this;
        }

        public Criteria andUranoNotLike(String value) {
            addCriterion("urano not like", value, "urano");
            return this;
        }

        public Criteria andUranoIn(List values) {
            addCriterion("urano in", values, "urano");
            return this;
        }

        public Criteria andUranoNotIn(List values) {
            addCriterion("urano not in", values, "urano");
            return this;
        }

        public Criteria andUranoBetween(String value1, String value2) {
            addCriterion("urano between", value1, value2, "urano");
            return this;
        }

        public Criteria andUranoNotBetween(String value1, String value2) {
            addCriterion("urano not between", value1, value2, "urano");
            return this;
        }

        public Criteria andTiIsNull() {
            addCriterion("ti is null");
            return this;
        }

        public Criteria andTiIsNotNull() {
            addCriterion("ti is not null");
            return this;
        }

        public Criteria andTiEqualTo(String value) {
            addCriterion("ti =", value, "ti");
            return this;
        }

        public Criteria andTiNotEqualTo(String value) {
            addCriterion("ti <>", value, "ti");
            return this;
        }

        public Criteria andTiGreaterThan(String value) {
            addCriterion("ti >", value, "ti");
            return this;
        }

        public Criteria andTiGreaterThanOrEqualTo(String value) {
            addCriterion("ti >=", value, "ti");
            return this;
        }

        public Criteria andTiLessThan(String value) {
            addCriterion("ti <", value, "ti");
            return this;
        }

        public Criteria andTiLessThanOrEqualTo(String value) {
            addCriterion("ti <=", value, "ti");
            return this;
        }

        public Criteria andTiLike(String value) {
            addCriterion("ti like", value, "ti");
            return this;
        }

        public Criteria andTiNotLike(String value) {
            addCriterion("ti not like", value, "ti");
            return this;
        }

        public Criteria andTiIn(List values) {
            addCriterion("ti in", values, "ti");
            return this;
        }

        public Criteria andTiNotIn(List values) {
            addCriterion("ti not in", values, "ti");
            return this;
        }

        public Criteria andTiBetween(String value1, String value2) {
            addCriterion("ti between", value1, value2, "ti");
            return this;
        }

        public Criteria andTiNotBetween(String value1, String value2) {
            addCriterion("ti not between", value1, value2, "ti");
            return this;
        }

        public Criteria andSize_maxIsNull() {
            addCriterion("size_max is null");
            return this;
        }

        public Criteria andSize_maxIsNotNull() {
            addCriterion("size_max is not null");
            return this;
        }

        public Criteria andSize_maxEqualTo(String value) {
            addCriterion("size_max =", value, "size_max");
            return this;
        }

        public Criteria andSize_maxNotEqualTo(String value) {
            addCriterion("size_max <>", value, "size_max");
            return this;
        }

        public Criteria andSize_maxGreaterThan(String value) {
            addCriterion("size_max >", value, "size_max");
            return this;
        }

        public Criteria andSize_maxGreaterThanOrEqualTo(String value) {
            addCriterion("size_max >=", value, "size_max");
            return this;
        }

        public Criteria andSize_maxLessThan(String value) {
            addCriterion("size_max <", value, "size_max");
            return this;
        }

        public Criteria andSize_maxLessThanOrEqualTo(String value) {
            addCriterion("size_max <=", value, "size_max");
            return this;
        }

        public Criteria andSize_maxLike(String value) {
            addCriterion("size_max like", value, "size_max");
            return this;
        }

        public Criteria andSize_maxNotLike(String value) {
            addCriterion("size_max not like", value, "size_max");
            return this;
        }

        public Criteria andSize_maxIn(List values) {
            addCriterion("size_max in", values, "size_max");
            return this;
        }

        public Criteria andSize_maxNotIn(List values) {
            addCriterion("size_max not in", values, "size_max");
            return this;
        }

        public Criteria andSize_maxBetween(String value1, String value2) {
            addCriterion("size_max between", value1, value2, "size_max");
            return this;
        }

        public Criteria andSize_maxNotBetween(String value1, String value2) {
            addCriterion("size_max not between", value1, value2, "size_max");
            return this;
        }

        public Criteria andSize_minIsNull() {
            addCriterion("size_min is null");
            return this;
        }

        public Criteria andSize_minIsNotNull() {
            addCriterion("size_min is not null");
            return this;
        }

        public Criteria andSize_minEqualTo(String value) {
            addCriterion("size_min =", value, "size_min");
            return this;
        }

        public Criteria andSize_minNotEqualTo(String value) {
            addCriterion("size_min <>", value, "size_min");
            return this;
        }

        public Criteria andSize_minGreaterThan(String value) {
            addCriterion("size_min >", value, "size_min");
            return this;
        }

        public Criteria andSize_minGreaterThanOrEqualTo(String value) {
            addCriterion("size_min >=", value, "size_min");
            return this;
        }

        public Criteria andSize_minLessThan(String value) {
            addCriterion("size_min <", value, "size_min");
            return this;
        }

        public Criteria andSize_minLessThanOrEqualTo(String value) {
            addCriterion("size_min <=", value, "size_min");
            return this;
        }

        public Criteria andSize_minLike(String value) {
            addCriterion("size_min like", value, "size_min");
            return this;
        }

        public Criteria andSize_minNotLike(String value) {
            addCriterion("size_min not like", value, "size_min");
            return this;
        }

        public Criteria andSize_minIn(List values) {
            addCriterion("size_min in", values, "size_min");
            return this;
        }

        public Criteria andSize_minNotIn(List values) {
            addCriterion("size_min not in", values, "size_min");
            return this;
        }

        public Criteria andSize_minBetween(String value1, String value2) {
            addCriterion("size_min between", value1, value2, "size_min");
            return this;
        }

        public Criteria andSize_minNotBetween(String value1, String value2) {
            addCriterion("size_min not between", value1, value2, "size_min");
            return this;
        }

        public Criteria andPaIsNull() {
            addCriterion("pa is null");
            return this;
        }

        public Criteria andPaIsNotNull() {
            addCriterion("pa is not null");
            return this;
        }

        public Criteria andPaEqualTo(String value) {
            addCriterion("pa =", value, "pa");
            return this;
        }

        public Criteria andPaNotEqualTo(String value) {
            addCriterion("pa <>", value, "pa");
            return this;
        }

        public Criteria andPaGreaterThan(String value) {
            addCriterion("pa >", value, "pa");
            return this;
        }

        public Criteria andPaGreaterThanOrEqualTo(String value) {
            addCriterion("pa >=", value, "pa");
            return this;
        }

        public Criteria andPaLessThan(String value) {
            addCriterion("pa <", value, "pa");
            return this;
        }

        public Criteria andPaLessThanOrEqualTo(String value) {
            addCriterion("pa <=", value, "pa");
            return this;
        }

        public Criteria andPaLike(String value) {
            addCriterion("pa like", value, "pa");
            return this;
        }

        public Criteria andPaNotLike(String value) {
            addCriterion("pa not like", value, "pa");
            return this;
        }

        public Criteria andPaIn(List values) {
            addCriterion("pa in", values, "pa");
            return this;
        }

        public Criteria andPaNotIn(List values) {
            addCriterion("pa not in", values, "pa");
            return this;
        }

        public Criteria andPaBetween(String value1, String value2) {
            addCriterion("pa between", value1, value2, "pa");
            return this;
        }

        public Criteria andPaNotBetween(String value1, String value2) {
            addCriterion("pa not between", value1, value2, "pa");
            return this;
        }

        public Criteria andS_classIsNull() {
            addCriterion("s_class is null");
            return this;
        }

        public Criteria andS_classIsNotNull() {
            addCriterion("s_class is not null");
            return this;
        }

        public Criteria andS_classEqualTo(String value) {
            addCriterion("s_class =", value, "s_class");
            return this;
        }

        public Criteria andS_classNotEqualTo(String value) {
            addCriterion("s_class <>", value, "s_class");
            return this;
        }

        public Criteria andS_classGreaterThan(String value) {
            addCriterion("s_class >", value, "s_class");
            return this;
        }

        public Criteria andS_classGreaterThanOrEqualTo(String value) {
            addCriterion("s_class >=", value, "s_class");
            return this;
        }

        public Criteria andS_classLessThan(String value) {
            addCriterion("s_class <", value, "s_class");
            return this;
        }

        public Criteria andS_classLessThanOrEqualTo(String value) {
            addCriterion("s_class <=", value, "s_class");
            return this;
        }

        public Criteria andS_classLike(String value) {
            addCriterion("s_class like", value, "s_class");
            return this;
        }

        public Criteria andS_classNotLike(String value) {
            addCriterion("s_class not like", value, "s_class");
            return this;
        }

        public Criteria andS_classIn(List values) {
            addCriterion("s_class in", values, "s_class");
            return this;
        }

        public Criteria andS_classNotIn(List values) {
            addCriterion("s_class not in", values, "s_class");
            return this;
        }

        public Criteria andS_classBetween(String value1, String value2) {
            addCriterion("s_class between", value1, value2, "s_class");
            return this;
        }

        public Criteria andS_classNotBetween(String value1, String value2) {
            addCriterion("s_class not between", value1, value2, "s_class");
            return this;
        }

        public Criteria andNstsIsNull() {
            addCriterion("nsts is null");
            return this;
        }

        public Criteria andNstsIsNotNull() {
            addCriterion("nsts is not null");
            return this;
        }

        public Criteria andNstsEqualTo(String value) {
            addCriterion("nsts =", value, "nsts");
            return this;
        }

        public Criteria andNstsNotEqualTo(String value) {
            addCriterion("nsts <>", value, "nsts");
            return this;
        }

        public Criteria andNstsGreaterThan(String value) {
            addCriterion("nsts >", value, "nsts");
            return this;
        }

        public Criteria andNstsGreaterThanOrEqualTo(String value) {
            addCriterion("nsts >=", value, "nsts");
            return this;
        }

        public Criteria andNstsLessThan(String value) {
            addCriterion("nsts <", value, "nsts");
            return this;
        }

        public Criteria andNstsLessThanOrEqualTo(String value) {
            addCriterion("nsts <=", value, "nsts");
            return this;
        }

        public Criteria andNstsLike(String value) {
            addCriterion("nsts like", value, "nsts");
            return this;
        }

        public Criteria andNstsNotLike(String value) {
            addCriterion("nsts not like", value, "nsts");
            return this;
        }

        public Criteria andNstsIn(List values) {
            addCriterion("nsts in", values, "nsts");
            return this;
        }

        public Criteria andNstsNotIn(List values) {
            addCriterion("nsts not in", values, "nsts");
            return this;
        }

        public Criteria andNstsBetween(String value1, String value2) {
            addCriterion("nsts between", value1, value2, "nsts");
            return this;
        }

        public Criteria andNstsNotBetween(String value1, String value2) {
            addCriterion("nsts not between", value1, value2, "nsts");
            return this;
        }

        public Criteria andBrstrIsNull() {
            addCriterion("brstr is null");
            return this;
        }

        public Criteria andBrstrIsNotNull() {
            addCriterion("brstr is not null");
            return this;
        }

        public Criteria andBrstrEqualTo(String value) {
            addCriterion("brstr =", value, "brstr");
            return this;
        }

        public Criteria andBrstrNotEqualTo(String value) {
            addCriterion("brstr <>", value, "brstr");
            return this;
        }

        public Criteria andBrstrGreaterThan(String value) {
            addCriterion("brstr >", value, "brstr");
            return this;
        }

        public Criteria andBrstrGreaterThanOrEqualTo(String value) {
            addCriterion("brstr >=", value, "brstr");
            return this;
        }

        public Criteria andBrstrLessThan(String value) {
            addCriterion("brstr <", value, "brstr");
            return this;
        }

        public Criteria andBrstrLessThanOrEqualTo(String value) {
            addCriterion("brstr <=", value, "brstr");
            return this;
        }

        public Criteria andBrstrLike(String value) {
            addCriterion("brstr like", value, "brstr");
            return this;
        }

        public Criteria andBrstrNotLike(String value) {
            addCriterion("brstr not like", value, "brstr");
            return this;
        }

        public Criteria andBrstrIn(List values) {
            addCriterion("brstr in", values, "brstr");
            return this;
        }

        public Criteria andBrstrNotIn(List values) {
            addCriterion("brstr not in", values, "brstr");
            return this;
        }

        public Criteria andBrstrBetween(String value1, String value2) {
            addCriterion("brstr between", value1, value2, "brstr");
            return this;
        }

        public Criteria andBrstrNotBetween(String value1, String value2) {
            addCriterion("brstr not between", value1, value2, "brstr");
            return this;
        }

        public Criteria andBchmIsNull() {
            addCriterion("bchm is null");
            return this;
        }

        public Criteria andBchmIsNotNull() {
            addCriterion("bchm is not null");
            return this;
        }

        public Criteria andBchmEqualTo(String value) {
            addCriterion("bchm =", value, "bchm");
            return this;
        }

        public Criteria andBchmNotEqualTo(String value) {
            addCriterion("bchm <>", value, "bchm");
            return this;
        }

        public Criteria andBchmGreaterThan(String value) {
            addCriterion("bchm >", value, "bchm");
            return this;
        }

        public Criteria andBchmGreaterThanOrEqualTo(String value) {
            addCriterion("bchm >=", value, "bchm");
            return this;
        }

        public Criteria andBchmLessThan(String value) {
            addCriterion("bchm <", value, "bchm");
            return this;
        }

        public Criteria andBchmLessThanOrEqualTo(String value) {
            addCriterion("bchm <=", value, "bchm");
            return this;
        }

        public Criteria andBchmLike(String value) {
            addCriterion("bchm like", value, "bchm");
            return this;
        }

        public Criteria andBchmNotLike(String value) {
            addCriterion("bchm not like", value, "bchm");
            return this;
        }

        public Criteria andBchmIn(List values) {
            addCriterion("bchm in", values, "bchm");
            return this;
        }

        public Criteria andBchmNotIn(List values) {
            addCriterion("bchm not in", values, "bchm");
            return this;
        }

        public Criteria andBchmBetween(String value1, String value2) {
            addCriterion("bchm between", value1, value2, "bchm");
            return this;
        }

        public Criteria andBchmNotBetween(String value1, String value2) {
            addCriterion("bchm not between", value1, value2, "bchm");
            return this;
        }

        public Criteria andNgcdescrIsNull() {
            addCriterion("ngcdescr is null");
            return this;
        }

        public Criteria andNgcdescrIsNotNull() {
            addCriterion("ngcdescr is not null");
            return this;
        }

        public Criteria andNgcdescrEqualTo(String value) {
            addCriterion("ngcdescr =", value, "ngcdescr");
            return this;
        }

        public Criteria andNgcdescrNotEqualTo(String value) {
            addCriterion("ngcdescr <>", value, "ngcdescr");
            return this;
        }

        public Criteria andNgcdescrGreaterThan(String value) {
            addCriterion("ngcdescr >", value, "ngcdescr");
            return this;
        }

        public Criteria andNgcdescrGreaterThanOrEqualTo(String value) {
            addCriterion("ngcdescr >=", value, "ngcdescr");
            return this;
        }

        public Criteria andNgcdescrLessThan(String value) {
            addCriterion("ngcdescr <", value, "ngcdescr");
            return this;
        }

        public Criteria andNgcdescrLessThanOrEqualTo(String value) {
            addCriterion("ngcdescr <=", value, "ngcdescr");
            return this;
        }

        public Criteria andNgcdescrLike(String value) {
            addCriterion("ngcdescr like", value, "ngcdescr");
            return this;
        }

        public Criteria andNgcdescrNotLike(String value) {
            addCriterion("ngcdescr not like", value, "ngcdescr");
            return this;
        }

        public Criteria andNgcdescrIn(List values) {
            addCriterion("ngcdescr in", values, "ngcdescr");
            return this;
        }

        public Criteria andNgcdescrNotIn(List values) {
            addCriterion("ngcdescr not in", values, "ngcdescr");
            return this;
        }

        public Criteria andNgcdescrBetween(String value1, String value2) {
            addCriterion("ngcdescr between", value1, value2, "ngcdescr");
            return this;
        }

        public Criteria andNgcdescrNotBetween(String value1, String value2) {
            addCriterion("ngcdescr not between", value1, value2, "ngcdescr");
            return this;
        }

        public Criteria andNotesIsNull() {
            addCriterion("notes is null");
            return this;
        }

        public Criteria andNotesIsNotNull() {
            addCriterion("notes is not null");
            return this;
        }

        public Criteria andNotesEqualTo(String value) {
            addCriterion("notes =", value, "notes");
            return this;
        }

        public Criteria andNotesNotEqualTo(String value) {
            addCriterion("notes <>", value, "notes");
            return this;
        }

        public Criteria andNotesGreaterThan(String value) {
            addCriterion("notes >", value, "notes");
            return this;
        }

        public Criteria andNotesGreaterThanOrEqualTo(String value) {
            addCriterion("notes >=", value, "notes");
            return this;
        }

        public Criteria andNotesLessThan(String value) {
            addCriterion("notes <", value, "notes");
            return this;
        }

        public Criteria andNotesLessThanOrEqualTo(String value) {
            addCriterion("notes <=", value, "notes");
            return this;
        }

        public Criteria andNotesLike(String value) {
            addCriterion("notes like", value, "notes");
            return this;
        }

        public Criteria andNotesNotLike(String value) {
            addCriterion("notes not like", value, "notes");
            return this;
        }

        public Criteria andNotesIn(List values) {
            addCriterion("notes in", values, "notes");
            return this;
        }

        public Criteria andNotesNotIn(List values) {
            addCriterion("notes not in", values, "notes");
            return this;
        }

        public Criteria andNotesBetween(String value1, String value2) {
            addCriterion("notes between", value1, value2, "notes");
            return this;
        }

        public Criteria andNotesNotBetween(String value1, String value2) {
            addCriterion("notes not between", value1, value2, "notes");
            return this;
        }
    }
}