package domain.model;

public class Sac_deepsky {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sac_deepsky.object
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    private String object;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sac_deepsky.other
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    private String other;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sac_deepsky.type
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    private String type;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sac_deepsky.con
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    private String con;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sac_deepsky.ra_hr
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    private String ra_hr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sac_deepsky.ra_min
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    private String ra_min;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sac_deepsky.dec_deg
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    private String dec_deg;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sac_deepsky.dec_min
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    private String dec_min;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sac_deepsky.mag
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    private String mag;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sac_deepsky.subr
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    private String subr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sac_deepsky.urano
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    private String urano;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sac_deepsky.ti
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    private String ti;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sac_deepsky.size_max
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    private String size_max;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sac_deepsky.size_min
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    private String size_min;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sac_deepsky.pa
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    private String pa;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sac_deepsky.s_class
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    private String s_class;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sac_deepsky.nsts
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    private String nsts;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sac_deepsky.brstr
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    private String brstr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sac_deepsky.bchm
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    private String bchm;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sac_deepsky.ngcdescr
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    private String ngcdescr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sac_deepsky.notes
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    private String notes;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sac_deepsky.object
     *
     * @return the value of sac_deepsky.object
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public String getObject() {
        return object;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sac_deepsky.object
     *
     * @param object the value for sac_deepsky.object
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public void setObject(String object) {
        this.object = object == null ? null : object.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sac_deepsky.other
     *
     * @return the value of sac_deepsky.other
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sac_deepsky.other
     *
     * @param other the value for sac_deepsky.other
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sac_deepsky.type
     *
     * @return the value of sac_deepsky.type
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sac_deepsky.type
     *
     * @param type the value for sac_deepsky.type
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sac_deepsky.con
     *
     * @return the value of sac_deepsky.con
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public String getCon() {
        return con;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sac_deepsky.con
     *
     * @param con the value for sac_deepsky.con
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public void setCon(String con) {
        this.con = con == null ? null : con.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sac_deepsky.ra_hr
     *
     * @return the value of sac_deepsky.ra_hr
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public String getRa_hr() {
        return ra_hr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sac_deepsky.ra_hr
     *
     * @param ra_hr the value for sac_deepsky.ra_hr
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public void setRa_hr(String ra_hr) {
        this.ra_hr = ra_hr == null ? null : ra_hr.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sac_deepsky.ra_min
     *
     * @return the value of sac_deepsky.ra_min
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public String getRa_min() {
        return ra_min;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sac_deepsky.ra_min
     *
     * @param ra_min the value for sac_deepsky.ra_min
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public void setRa_min(String ra_min) {
        this.ra_min = ra_min == null ? null : ra_min.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sac_deepsky.dec_deg
     *
     * @return the value of sac_deepsky.dec_deg
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public String getDec_deg() {
        return dec_deg;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sac_deepsky.dec_deg
     *
     * @param dec_deg the value for sac_deepsky.dec_deg
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public void setDec_deg(String dec_deg) {
        this.dec_deg = dec_deg == null ? null : dec_deg.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sac_deepsky.dec_min
     *
     * @return the value of sac_deepsky.dec_min
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public String getDec_min() {
        return dec_min;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sac_deepsky.dec_min
     *
     * @param dec_min the value for sac_deepsky.dec_min
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public void setDec_min(String dec_min) {
        this.dec_min = dec_min == null ? null : dec_min.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sac_deepsky.mag
     *
     * @return the value of sac_deepsky.mag
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public String getMag() {
        return mag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sac_deepsky.mag
     *
     * @param mag the value for sac_deepsky.mag
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public void setMag(String mag) {
        this.mag = mag == null ? null : mag.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sac_deepsky.subr
     *
     * @return the value of sac_deepsky.subr
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public String getSubr() {
        return subr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sac_deepsky.subr
     *
     * @param subr the value for sac_deepsky.subr
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public void setSubr(String subr) {
        this.subr = subr == null ? null : subr.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sac_deepsky.urano
     *
     * @return the value of sac_deepsky.urano
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public String getUrano() {
        return urano;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sac_deepsky.urano
     *
     * @param urano the value for sac_deepsky.urano
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public void setUrano(String urano) {
        this.urano = urano == null ? null : urano.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sac_deepsky.ti
     *
     * @return the value of sac_deepsky.ti
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public String getTi() {
        return ti;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sac_deepsky.ti
     *
     * @param ti the value for sac_deepsky.ti
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public void setTi(String ti) {
        this.ti = ti == null ? null : ti.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sac_deepsky.size_max
     *
     * @return the value of sac_deepsky.size_max
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public String getSize_max() {
        return size_max;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sac_deepsky.size_max
     *
     * @param size_max the value for sac_deepsky.size_max
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public void setSize_max(String size_max) {
        this.size_max = size_max == null ? null : size_max.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sac_deepsky.size_min
     *
     * @return the value of sac_deepsky.size_min
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public String getSize_min() {
        return size_min;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sac_deepsky.size_min
     *
     * @param size_min the value for sac_deepsky.size_min
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public void setSize_min(String size_min) {
        this.size_min = size_min == null ? null : size_min.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sac_deepsky.pa
     *
     * @return the value of sac_deepsky.pa
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public String getPa() {
        return pa;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sac_deepsky.pa
     *
     * @param pa the value for sac_deepsky.pa
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public void setPa(String pa) {
        this.pa = pa == null ? null : pa.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sac_deepsky.s_class
     *
     * @return the value of sac_deepsky.s_class
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public String getS_class() {
        return s_class;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sac_deepsky.s_class
     *
     * @param s_class the value for sac_deepsky.s_class
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public void setS_class(String s_class) {
        this.s_class = s_class == null ? null : s_class.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sac_deepsky.nsts
     *
     * @return the value of sac_deepsky.nsts
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public String getNsts() {
        return nsts;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sac_deepsky.nsts
     *
     * @param nsts the value for sac_deepsky.nsts
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public void setNsts(String nsts) {
        this.nsts = nsts == null ? null : nsts.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sac_deepsky.brstr
     *
     * @return the value of sac_deepsky.brstr
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public String getBrstr() {
        return brstr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sac_deepsky.brstr
     *
     * @param brstr the value for sac_deepsky.brstr
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public void setBrstr(String brstr) {
        this.brstr = brstr == null ? null : brstr.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sac_deepsky.bchm
     *
     * @return the value of sac_deepsky.bchm
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public String getBchm() {
        return bchm;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sac_deepsky.bchm
     *
     * @param bchm the value for sac_deepsky.bchm
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public void setBchm(String bchm) {
        this.bchm = bchm == null ? null : bchm.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sac_deepsky.ngcdescr
     *
     * @return the value of sac_deepsky.ngcdescr
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public String getNgcdescr() {
        return ngcdescr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sac_deepsky.ngcdescr
     *
     * @param ngcdescr the value for sac_deepsky.ngcdescr
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public void setNgcdescr(String ngcdescr) {
        this.ngcdescr = ngcdescr == null ? null : ngcdescr.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sac_deepsky.notes
     *
     * @return the value of sac_deepsky.notes
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sac_deepsky.notes
     *
     * @param notes the value for sac_deepsky.notes
     *
     * @abatorgenerated Wed Mar 29 22:36:26 CST 2017
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }
}